### ISSUE TITLE
file db toko buku php 5

### ISSUE THREAD

**Issue by taraktadung** [EChristian48/Toko-Buku-PHP-5#1]
pak, file databasenya .sql nya ketinggalan. 
mohon diunggah lagi pak file dbnya
terima kasih

**Comment by EChristian48** [comment]
Emang belum beres mas, ini dapet dari temen saya, dia suruh masukin GItHub saya aja
Mending cek aja aplikasinya, terus liat db/table/column yang missing, terus dibuat db-nya dari situ
